name: 'Build dependency package locally'
description: 'Checks out a dependency package locally and updates all references to it'
inputs:
  package:
    description: 'Name of the package'
    required: true
  download_dependencies:
    description: 'Whether to download dependencies'
    default: 'false'
  skip_build:
    description: 'Whether to skip the build'
    default: 'false'
  skip_tests:
    description: 'Whether to skip the tests'
    default: 'false'
  target_artifact:
    description: 'Name of the artifact that will be uploaded'
    default: 'dependencies'
  artifact_path:
    description: 'Path or pattern for the artifact files that should be uploaded'
  token:
    description: 'Personal Access Token to checkout the repository'
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - name: Clone
      uses: actions/checkout@v2
      with:
        repository: cloudscape-design/${{ inputs.package }}
        token: ${{ inputs.token }}
        path: ${{ inputs.package }}
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Download artifacts
      if: ${{ inputs.download_dependencies == 'true' }}
      uses: actions/download-artifact@v2
      with:
        name: dependencies

    - run: cd ${{ inputs.package }}
      shell: bash

    - uses: ./.github/actions/patch-local-dependencies
      with:
        path: ${{ github.workspace }}/${{ inputs.package }}
        type: local

    - name: npm install
      shell: bash
      run: npm i
      working-directory: ${{ inputs.package }}
    - name: Build
      if: ${{ inputs.skip_build != 'true' }}
      shell: bash
      run: npm run build
      working-directory: ${{ inputs.package }}
    - name: Test
      if: ${{ inputs.skip_tests != 'true' }}
      shell: bash
      run: npm test
      working-directory: ${{ inputs.package }}
    - name: Pack artifacts
      if: ${{ inputs.package != 'components' && inputs.package != 'test-utils' && inputs.package != 'theming-core' }}
      shell: bash
      working-directory: ${{ inputs.package }}
      run: |
        npm pack
        cp *-${{ inputs.package }}-*.tgz $GITHUB_WORKSPACE/${{ inputs.package }}.tgz

    - name: Pack test-utils artifacts
      if: ${{ inputs.package == 'test-utils' }}
      shell: bash
      working-directory: ${{ inputs.package }}
      run: |
        cd packages/core
        npm pack
        cp *-test-utils-core-*.tgz $GITHUB_WORKSPACE
        cd ../converter
        npm pack
        echo $GITHUB_WORKSPACE
        cp *-test-utils-converter-*.tgz $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        mv *-test-utils-converter-*.tgz test-utils-converter.tgz
        mv *-test-utils-core-*.tgz test-utils-core.tgz

    - name: Pack theming-core artifacts
      if: ${{ inputs.package == 'theming-core' }}
      shell: bash
      working-directory: ${{ inputs.package }}
      run: |
        cd lib/browser
        npm pack
        cp *-theming-runtime-*.tgz $GITHUB_WORKSPACE
        cd ../node
        npm pack
        echo $GITHUB_WORKSPACE
        cp *-theming-build-*.tgz $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        mv *-theming-build-*.tgz theming-build.tgz
        mv *-theming-runtime-*.tgz theming-runtime.tgz

    - name: Package component files
      if: ${{ inputs.package == 'components' }}
      shell: bash
      working-directory: ${{ inputs.package }}
      run: tar -czf ../components.tgz --strip-components=1 .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.target_artifact }}
        path: ${{ inputs.artifact_path || format('{0}*.tgz', inputs.package) }}
