// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

const { series, parallel, watch } = require('gulp');
const themes = require('./build-tools/utils/themes');
const { task } = require('./build-tools/utils/gulp-utils');
const {
  clean,
  docs,
  generateEnvironment,
  generateIcons,
  generateIndexFile,
  generateCustomCssPropertiesMap,
  packageJSON,
  unit,
  styles,
  typescript,
  buildPages,
  testUtils,
  a11y,
  generateI18nMessages,
  integ,
  motion,
  copyFiles,
  themeableSource,
  bundleVendorFiles,
  sizeLimit,
  testDefinitions,
} = require('./build-tools/tasks');

const assertCompositionNotStale = task('assertCompositionNotStale', () => {
  themes.assertCompositionUnchanged();
  return Promise.resolve();
});

const quickBuild = series(
  clean,
  parallel(packageJSON, generateI18nMessages, generateEnvironment, generateIcons, generateIndexFile, copyFiles),
  parallel(generateCustomCssPropertiesMap, styles, typescript, testUtils),
  bundleVendorFiles
);

exports.clean = clean;
exports['quick-build'] = quickBuild;
exports.i18n = generateI18nMessages;
exports.build = series(quickBuild, parallel(buildPages, themeableSource, docs, sizeLimit, testDefinitions));
exports['build:test-definitions'] = testDefinitions;
exports.test = series(unit, integ, a11y);
exports['test:unit'] = unit;
exports['test:integ'] = integ;
exports['test:a11y'] = a11y;
exports['test:motion'] = motion;

exports.watch = () => {
  watch(
    [
      'src/**/*.{ts,tsx}',
      '!src/test-utils/**/*.ts',
      '!**/__tests__/**',
      '!**/__integ__/**',
      '!**/__a11y__/**',
      '!**/__motion__/**',
      '!src/internal/vendor/**/*.ts',
      // Generated by generateIndexFile/generateIcons/generateCustomCssPropertiesMap during
      // quick-build — none of those tasks are in this watch pipeline, so nothing here ever
      // regenerates them; the only way they change while `gulp watch` is running is a SEPARATE,
      // concurrent quick-build. Watching them means that other process's writes pointlessly
      // retrigger this session's tasks (or, for the styles glob below, retrigger them with THIS
      // session's own stale composition — see the styles/generateEnvironment watch entry).
      '!src/index.ts',
      '!src/icon/generated/**',
      '!src/internal/generated/custom-css-properties/**',
    ],
    typescript
  );
  watch(['src/i18n/messages/*.json'], generateI18nMessages);
  watch(['src/test-utils/dom/**/*.ts', '!src/test-utils/dom/index.ts'], testUtils);
  // generateEnvironment is included here so `lib/components/internal/environment.*`
  // (PRIMARY_THEME/INCLUDED_THEMES/ALWAYS_VISUAL_REFRESH) never goes stale relative to what
  // `styles` is actually (re-)producing for this process's resolved theme composition.
  // assertCompositionNotStale runs first: if some OTHER process (e.g. a separate `quick-build`
  // run while this watch session is alive) changed what's actually built in lib/, this session's
  // own captured composition is stale — abort loudly rather than silently overwriting the other
  // build's output with this session's outdated one.
  watch(
    ['style-dictionary/**/*.ts', 'src/**/*.scss', '!src/internal/generated/custom-css-properties/**'],
    series(assertCompositionNotStale, generateEnvironment, styles)
  );
};
