export const allProperties = [
  'backgroundColor',
  'backgroundImage',
  'borderColor',
  'borderRadius',
  'borderWidth',
  'boxShadow',
  'color',
  'fill',
  'fontFamily',
  'fontSize',
  'fontStyle',
  'fontWeight',
  'gapBlock',
  'gapInline',
  'height',
  'lineHeight',
  'outline',
  'paddingBlock',
  'paddingInline',
  'width',
];

export const allStatesAndSemantics = [
  'active',
  'critical',
  'default',
  'checked',
  'disabled',
  'empty',
  'error',
  'focus',
  'high',
  'hover',
  'indeterminate',
  'info',
  'invalid',
  'loading',
  'low',
  'medium',
  'neutral',
  'normal',
  'readOnly',
  'selected',
  'success',
  'valid',
  'visited',
  'warning',
];

export const darkModeProperties = [
  'backgroundColor',
  'backgroundImage',
  'borderColor',
  'boxShadow',
  'color',
  'fill',
  'outline',
];

export const propertiesWithState = [
  'backgroundColor',
  'backgroundImage',
  'borderColor',
  'boxShadow',
  'color',
  'fill',
  'fontStyle',
  'outline'
];