// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
// Auto-generated by build-tools/visual/generate-tests.js — do not edit manually.
import { runTestSuites } from '../definitions/utils';
import suite from '../definitions/visual/action-card';

runTestSuites([suite]);
