name: Documentation
description: Report an issue or suggest an improvement in our documentation website
title: '[Documentation]: '
labels: documentation
body:
  - type: markdown
    attributes:
      value: Use this template to report an issue or suggest an improvement in our [documentation website](https://cloudscape.design/).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the issue or the suggested improvement
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/cloudscape-design/components/issues) for duplicate requests