name: Figma - Feture request
description: Request a feature for our [Figma libraries](https://www.figma.com/@cloudscape).
labels: enhancement,design,figma
body:
  - type: markdown
    attributes:
      value: Use this template to request a feature for our [Figma libraries](https://www.figma.com/@cloudscape).
  - type: textarea
    attributes:
      label: Describe the feature
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/cloudscape-design/components/issues) for duplicate requests
