// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

import { TestSuite } from '../types';

const suite: TestSuite = {
  description: 'ContentLayout permutations',
  componentName: 'content-layout',
  tests: [
    // default headerVariant
    {
      description: 'default headerVariant, none headerBackgroundStyle, at 1400, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'default headerVariant, none headerBackgroundStyle, at 1400, with notifications and breadcrumbs',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'default headerVariant, none headerBackgroundStyle, at 600, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 600 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'default headerVariant, none headerBackgroundStyle, at 600, with notifications and breadcrumbs',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 600 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'default headerVariant, none headerBackgroundStyle, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
        maxContentWidth: '1000',
      },
    },
    // default headerVariant, gradient
    {
      description: 'default headerVariant, gradient headerBackgroundStyle, at 1400, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'gradient',
      },
    },
    {
      description: 'default headerVariant, gradient headerBackgroundStyle, at 1400, with notifications and breadcrumbs',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'gradient',
      },
    },
    {
      description: 'default headerVariant, gradient headerBackgroundStyle, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'gradient',
        maxContentWidth: '1000',
      },
    },
    // high-contrast headerVariant, none
    {
      description: 'high-contrast headerVariant, none headerBackgroundStyle, at 1400, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description:
        'high-contrast headerVariant, none headerBackgroundStyle, at 1400, with notifications and breadcrumbs',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'high-contrast headerVariant, none headerBackgroundStyle, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
        maxContentWidth: '1000',
      },
    },
    // high-contrast headerVariant, gradient
    {
      description: 'high-contrast headerVariant, gradient headerBackgroundStyle, at 1400, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'gradient',
      },
    },
    {
      description:
        'high-contrast headerVariant, gradient headerBackgroundStyle, at 1400, with notifications and breadcrumbs',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'gradient',
      },
    },
    {
      description: 'high-contrast headerVariant, gradient headerBackgroundStyle, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'gradient',
        maxContentWidth: '1000',
      },
    },
    // divider headerVariant
    {
      description: 'divider headerVariant, at 1400, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'divider',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'divider headerVariant, at 1400, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'true',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'false',
        defaultPadding: 'true',
        headerVariant: 'divider',
        headerBackgroundStyle: 'none',
        maxContentWidth: '1000',
      },
    },
    {
      description: 'divider headerVariant, at 600, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 600 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'divider',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'divider headerVariant, at 600, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 600 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'true',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'false',
        defaultPadding: 'true',
        headerVariant: 'divider',
        headerBackgroundStyle: 'none',
        maxContentWidth: '1000',
      },
    },
    // with app layout
    {
      description: 'with app layout, divider headerVariant, at 1400, simple',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'true',
        hasAppLayout: 'true',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'false',
        defaultPadding: 'true',
        headerVariant: 'divider',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'with app layout, high-contrast gradient, at 1400, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'true',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'gradient',
        maxContentWidth: '800',
      },
    },
    {
      description: 'with open navigation, without maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'true',
        hasAppLayoutWithOpenNavigation: 'true',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'with open navigation, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'true',
        hasNotifications: 'true',
        disableOverlap: 'false',
        hasAppLayout: 'true',
        hasAppLayoutWithOpenNavigation: 'true',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'divider',
        headerBackgroundStyle: 'none',
        maxContentWidth: '700',
      },
    },
    // with secondary header
    {
      description: 'with secondary header, at 1400',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'true',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'with secondary header, at 600',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 600 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'true',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'with secondary header, with maxContentWidth',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'true',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
        maxContentWidth: '900',
      },
    },
    // without header
    {
      description: 'without header, at 1400, defaultPadding=true, default headerVariant',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'true',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'without header, at 1400, defaultPadding=true, high-contrast headerVariant',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'true',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'without header, at 1400, defaultPadding=true, divider headerVariant',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'true',
        hasContainer: 'true',
        defaultPadding: 'true',
        headerVariant: 'divider',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'without header, at 1400, defaultPadding=false, default headerVariant',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'true',
        hasContainer: 'true',
        defaultPadding: 'false',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    // without default padding
    {
      description: 'without default padding, at 1400',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'false',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'without default padding, at 600',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 600 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'false',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'true',
        defaultPadding: 'false',
        headerVariant: 'default',
        headerBackgroundStyle: 'none',
      },
    },
    // with disabled overlap
    {
      description: 'with disabled overlap, at 1400',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 1400 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'true',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'false',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
    {
      description: 'with disabled overlap, at 600',
      path: 'content-layout/permutations',
      screenshotType: 'screenshotArea',
      configuration: { width: 600 },
      queryParams: {
        hasBreadcrumbs: 'false',
        hasNotifications: 'false',
        disableOverlap: 'true',
        hasAppLayout: 'false',
        hasAppLayoutWithOpenNavigation: 'false',
        hasSecondaryHeader: 'false',
        removeHeader: 'false',
        hasContainer: 'false',
        defaultPadding: 'true',
        headerVariant: 'high-contrast',
        headerBackgroundStyle: 'none',
      },
    },
  ],
};

export default suite;
