// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Auto-generates test/visual/*.test.ts files from test/definitions/visual/*.ts.
 *
 * Each definition file that exports a default TestSuite gets a corresponding
 * test runner. Helper files (those without a default export, e.g. shared utils
 * like app-layout-responsive-tests.ts) are skipped.
 *
 * Run this script before executing the visual test suite:
 *   node build-tools/visual/generate-tests.js
 */
const fs = require('fs');
const path = require('path');

const definitionsDir = path.resolve(__dirname, '../../test/definitions/visual');
const outputDir = path.resolve(__dirname, '../../test/visual');

// Files that are shared helpers (export named functions, not a default suite).
// These are detected by checking if the file contains "export default" or
// a conventional "const suite" pattern followed by "export default suite".
const HELPER_SUFFIXES = ['-tests'];

function isHelperFile(basename) {
  return HELPER_SUFFIXES.some(suffix => basename.endsWith(suffix));
}

function generate() {
  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const files = fs.readdirSync(definitionsDir).filter(f => f.endsWith('.ts') && !f.endsWith('.d.ts'));

  const generated = [];

  for (const file of files) {
    const basename = file.replace(/\.ts$/, '');

    if (isHelperFile(basename)) {
      continue;
    }

    // Verify the file has a default export by scanning for the pattern
    const content = fs.readFileSync(path.join(definitionsDir, file), 'utf-8');
    if (!content.includes('export default')) {
      continue;
    }

    const testContent = [
      '// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.',
      '// SPDX-License-Identifier: Apache-2.0',
      '// Auto-generated by build-tools/visual/generate-tests.js — do not edit manually.',
      `import { runTestSuites } from '../definitions/utils';`,
      `import suite from '../definitions/visual/${basename}';`,
      '',
      'runTestSuites([suite]);',
      '',
    ].join('\n');

    const outputPath = path.join(outputDir, `${basename}.test.ts`);
    fs.writeFileSync(outputPath, testContent);
    generated.push(basename);
  }

  console.log(`Generated ${generated.length} visual test files in test/visual/`);
}

generate();
