// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Auto-generates:
 *   1. test/visual/*.test.ts — one test runner per definition file (for Jest sharding)
 *   2. test/definitions/index.ts — barrel that exports allSuites from all definitions
 *
 * Each definition file that exports a default TestSuite gets included.
 * Helper files (those without a default export, e.g. shared utils like
 * app-layout-responsive-tests.ts) are skipped.
 *
 * Run this script before executing the visual test suite:
 *   node build-tools/visual/generate-tests.js
 */
const fs = require('fs');
const path = require('path');

const definitionsDir = path.resolve(__dirname, '../../test/definitions/visual');
const testOutputDir = path.resolve(__dirname, '../../test/visual');
const indexOutputPath = path.resolve(__dirname, '../../test/definitions/index.ts');

// Files that are shared helpers (export named functions, not a default suite).
const HELPER_SUFFIXES = ['-tests'];

function isHelperFile(basename) {
  return HELPER_SUFFIXES.some(suffix => basename.endsWith(suffix));
}

function toCamelCase(basename) {
  return basename.replace(/-([a-z0-9])/g, (_, char) => char.toUpperCase());
}

function generate() {
  // Ensure output directory exists
  if (!fs.existsSync(testOutputDir)) {
    fs.mkdirSync(testOutputDir, { recursive: true });
  }

  const files = fs.readdirSync(definitionsDir).filter(f => f.endsWith('.ts') && !f.endsWith('.d.ts'));

  const suiteFiles = [];

  for (const file of files) {
    const basename = file.replace(/\.ts$/, '');

    if (isHelperFile(basename)) {
      continue;
    }

    // Verify the file has a default export by scanning for the pattern
    const content = fs.readFileSync(path.join(definitionsDir, file), 'utf-8');
    if (!content.includes('export default')) {
      continue;
    }

    suiteFiles.push(basename);

    // Generate test/visual/<basename>.test.ts
    const testContent = [
      '// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.',
      '// SPDX-License-Identifier: Apache-2.0',
      '// Auto-generated by build-tools/visual/generate-tests.js — do not edit manually.',
      `import { runTestSuites } from '../definitions/utils';`,
      `import suite from '../definitions/visual/${basename}';`,
      '',
      'runTestSuites([suite]);',
      '',
    ].join('\n');

    fs.writeFileSync(path.join(testOutputDir, `${basename}.test.ts`), testContent);
  }

  // Generate test/definitions/index.ts
  // Sort by module path for consistent import ordering
  suiteFiles.sort();

  const imports = suiteFiles.map(basename => {
    const varName = toCamelCase(basename);
    return `import ${varName} from './visual/${basename}';`;
  });

  const arrayEntries = suiteFiles.map(basename => `  ${toCamelCase(basename)},`);

  const indexContent = [
    '// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.',
    '// SPDX-License-Identifier: Apache-2.0',
    '// Auto-generated by build-tools/visual/generate-tests.js — do not edit manually.',
    '',
    `import { TestSuite } from './types';`,
    `export { TestSuite, TestDefinition, ScreenshotType, ScreenshotTestConfiguration } from './types';`,
    ...imports,
    '',
    'export const allSuites: TestSuite[] = [',
    ...arrayEntries,
    '];',
    '',
  ].join('\n');

  fs.writeFileSync(indexOutputPath, indexContent);

  console.log(`Generated ${suiteFiles.length} visual test files in test/visual/`);
  console.log(`Generated test/definitions/index.ts with ${suiteFiles.length} suites`);
}

generate();
