name: Dependabot lockfile cleanup

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: write

jobs:
  cleanup:
    uses: cloudscape-design/actions/.github/workflows/dependabot-lockfile-cleanup.yml@main
    secrets: inherit
